###
# ```{rubric} Container image settings
# ```
# ---
# Define the image, tag and repository to be deployed.
#
# The `tag`{l=yaml} attribute overrides the image tag whose default is
# the chart `appVersion`{l=yaml}.
#
# In this repository, the image tag should match the latest released version
# of the Chart.
#
# ```{literalinclude} /values.yaml
# :caption: certmanager
# :language: yaml
# :start-at: "certmanager:\n"
# :end-before: "###\n"
# ```
certmanager:
  enabled: true
image:
  pullPolicy: Always
  repository: edwardtheharris/bitcoin-node
  tag: '0.0.1'

###
# ```{rubric} Ingress
# ```
# ---
# Configure Ingress for the service.
#
# ```{literalinclude} /values.yaml
# :caption: ingress
# :language: yaml
# :start-at: "ingress:\n"
# :end-before: "###\n"
# ```
#
# ```{code-block} yaml
# :caption: tls example
# tls:
#  - secretName: chart-example-tls
#    hosts:
#      - chart-example.local
# ```
ingress:
  annotations: {}
  className: nginx
  enabled: true
  externalIPs: []
  hosts:
  - host: bitcoin.breeze-blocks.net
    paths:
    - path: /
      pathType: Prefix
      port: 8333
      serviceName: bitcoin
  loadBalancerIP: ''
  secret:
    enabled: false
    crt: ''
    key: ''
  tls: []
labels:
  node: k8s10.breeze-blocks.net


###
# ```{rubric} Node Selector
# ```
# ---
# Select node(s) for workloads to run on.
#
# ```{literalinclude} /values.yaml
# :caption: affinity
# :language: yaml
# :start-at: "nodeSelector:\n"
# :end-before: "###\n"
# ```
nodeSelector:
  kubernetes.io/node: k8s10.breeze-blocks.net

###
# ```{rubric} Persistence Configuration
# ```
# ---
# Provision persistent storage if required.
#
# ```{literalinclude} /values.yaml
# :caption: persistence
# :language: yaml
# :start-at: "persistence:\n"
# :end-before: "###\n"
# ```
persistence:
  claim:
    enabled: true
  name: bitcoin
  storage:
    requests: 900Gi
    limits: 900Gi
  storageClass: csi-lvm-linear

###
# ```{rubric} Replica Count
# ```
# ---
# Deploy this many replicas by default.
#
# ```{literalinclude} /values.yaml
# :caption: replicas
# :language: yaml
# :start-at: "replicaCount: 1\n"
# :end-before: "###\n"
# ```
replicaCount: 1

###
# ```{rubric} Resource Requests and Limits
# ```
# ---
# Set requests and limits for workload resources.
#
# ```{literalinclude} /values.yaml
# :caption: resources
# :language: yaml
# :start-at: "resources:\n"
# :end-before: "###\n"
# ```
#
# We usually recommend not to specify default resources and to leave this as
# a conscious choice for the user. This also increases chances charts run on
# environments with little resources, such as Minikube. If you do want to
# specify resources, uncomment the following lines, adjust them as necessary,
# and remove the curly braces after `resources:`{l=yaml}.
#
# ```{code-block} yaml
# :caption: resources example
#
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi
# ```
resources:
  limits:
    cpu: 4
    memory: 6144Mi
  requests:
    cpu: 2
    memory: 4096Mi

###
# ```{rubric} Service
# ```
# ---
# Define the service used to access the application.
#
# ```{literalinclude} /values.yaml
# :caption: service
# :language: yaml
# :start-at: "service:\n"
# :end-before: "###\n"
# ```
#
# ```{code-block} yaml
# :caption: capabilities example
# capabilities:
#   drop:
#   - ALL
# readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000
# ```
service:
  enabled: true
  rest:
    name: rest
    port: 8333
    protocol: TCP
    targetPort: 8333
  rpc:
    enabled: true
    name: rpc
    port: 8334
    protocol: TCP
    targetPort: 8334
  type: LoadBalancer
  loadBalancerIP: 192.168.5.5
  externalIPs:
    - 192.168.5.20

###
# ```{rubric} Service Account
# ```
# ---
# When enabled, will create a Kubernetes Service Account during deployment.
#
# ```{literalinclude} /values.yaml
# :caption: serviceAccount
# :language: yaml
# :start-at: "serviceAccount:\n"
# :end-before: "###\n"
# ```
serviceAccount:
  # Annotations to add to the service account
  annotations:
    app.kubernetes.io/name: bitcoin
    app.kubernetes.io/instance: bitcoin
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname bitcoin-node
  name: "bitcoin"
statefulset:
  replicas: 1

###
# ```{rubric} Type
# ```
# ---
# May be set to `Deployment` or `StatefulSet`.
#
# ```{literalinclude} /values.yaml
# :caption: type
# :language: yaml
# :start-at: "type: StatefulSet\n"
# :end-before: "###\n"
# ```
type: StatefulSet
