{{- if .Values.certmanager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: 0.18.3.4-2
    helm.sh/chart: {{ .Chart.Name }}-0.0.2
  name: {{ .Release.Name }}
spec:
  dnsNames:
    - bitcoin.breeze-blocks.net
  ipAddresses:
    - 192.168.0.20
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: breeze-blocks-ca
  secretName: {{ .Release.Name }}-tls
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
{{- end }}
