apiVersion: v1
kind: Service
metadata:
  name: {{ include "bitcoin.fullname" . }}
  labels:
    {{- include "bitcoin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8333
      targetPort: 8333
      protocol: TCP
      name: rest
    - port: 8334
      targetPort: 8334
      protocol: TCP
      name: rpc
  selector:
    {{- include "bitcoin.selectorLabels" . | nindent 4 }}
