apiVersion: v1
kind: Service
metadata:
  name: {{ include "bitcoin.fullname" . }}
  labels:
    {{- include "bitcoin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.rest.port }}
      targetPort: {{ .Values.service.rest.targetPort }}
      protocol: {{ .Values.service.rest.protocol }}
      name: {{ .Values.service.rest.name }}
{{- if .Values.service.rpc.enabled }}
    - port: {{ .Values.service.rpc.port }}
      targetPort: {{ .Values.service.rpc.targetPort }}
      protocol: {{ .Values.service.rpc.protocol }}
      name: {{ .Values.service.rpc.name }}
{{- end }}
  selector:
    {{- include "bitcoin.selectorLabels" . | nindent 4 }}
