apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.nameOverride }}
  labels:
    {{- include "bitcoin.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "bitcoin.selectorLabels" . | nindent 6 }}
  serviceName: {{ .Values.nameOverride }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "bitcoin.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.nameOverride }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8333
              name: rest
            - containerPort: 8334
              name: rpc
          volumeMounts:
            - name: {{ .Values.nameOverride }}
              mountPath: /srv/bitcoin
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.nameOverride }}
      annotations:
        {{- include "bitcoin.selectorLabels" . | nindent 8 }}
        volume.kubernetes.io/selected-node: {{ .Values.labels.node }}
      labels:
        {{- include "bitcoin.labels" . | nindent 8 }}
    spec:
      accessModes: [ "ReadWriteMany", "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.persistence.size }}
      storageClassName: csi-lvm-linear
      volumeMode: Filesystem
