apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "bitcoin.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "bitcoin.selectorLabels" . | nindent 6 }}
  serviceName: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "bitcoin.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.rest.port }}
              name: {{ .Values.service.rest.name }}
            {{- if .Values.service.rpc.enabled }}
            - containerPort: {{ .Values.service.rpc.port }}
              name: {{ .Values.service.rpc.name }}
            {{- end }}
          volumeMounts:
            - name: {{ .Release.Name }}
              mountPath: /srv/bitcoin
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Release.Name }}
      annotations:
        {{- include "bitcoin.selectorLabels" . | nindent 8 }}
        volume.kubernetes.io/selected-node: {{ .Values.labels.node }}
      labels:
        {{- include "bitcoin.labels" . | nindent 8 }}
    spec:
      accessModes: [ "ReadWriteMany", "ReadWriteOnce" ]
      resources:
        limits:
          storage: {{ .Values.persistence.storage.limits }}
        requests:
          storage: {{ .Values.persistence.storage.requests }}
      storageClassName: csi-lvm-linear
      volumeMode: Filesystem
